spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ifjobs
    username: root
    password: 14062004Evelyn
    # password: h3tielle021004.
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  #level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework.web.servlet: DEBUG
    #org.springframework.security: DEBUG